meta:
  version: v1.0
agents:
  - DB1:
      version: 1
      host: localhost
      port: 3500
      enabled: True
  - iota:
      version: 1
      host: localhost
      port: 4000
      enabled: False


